-- Sector / colony / village -> MCG ward (2023 delimitation, 36 wards, 2025 council).
-- Generated from data/area-wards.csv; see docs/area-wards-notes.md for sources and caveats.
-- Rows whose note contains "verify" are suggestions for the desk, not confirmed boundaries.
-- Safe to re-run: upserts on area, never deletes.

insert into public.area_wards (area, ward, note) values
  ('Nathupur', 1, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('DLF Phase 3', 1, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 24', 1, 'press, verify; derived: DLF Phase 3 occupies Sector 24'),
  ('National Media Centre', 1, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Ambience Island', 1, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Garden Estate', 1, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('DLF Corporate Park', 1, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sikanderpur', 1, 'press, verify; Sikanderpur Ghosi village listed with ward 1 (newzpapr, Samvada)'),
  ('DLF Phase 2', 2, 'press report of final notification (Amar Ujala, 17 Dec 2023); whole of DLF 2 (the Aug 2023 draft had put J and Q blocks in ward 1)'),
  ('DLF Cyber City', 2, 'press report of final notification (Amar Ujala, 17 Dec 2023) (listed as DLF Cyber Hub)'),
  ('Sector 25', 2, 'press, verify; derived: DLF Phase 2 / Cyber Hub occupy Sector 25'),
  ('Udyog Vihar', 2, 'press report of final notification (Amar Ujala, 17 Dec 2023); Phases 1-5 (Phase 6 is in ward 9)'),
  ('Sector 18', 2, 'press, verify; Maruti Industries listed in ward 2; Sector 18 is the Maruti/Udyog Vihar industrial sector'),
  ('Sirhaul', 2, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Dundahera', 2, 'press, verify; Samvada (2024) and newzpapr list Dundahera in ward 2'),
  ('Surya Vihar', 2, 'press, verify; the Surya Vihar near Dundahera; a colony of the same name near Sector 7 is listed with ward 32'),
  ('Heritage City', 2, 'press (newzpapr ward list), verify'),
  ('Beverly Park', 2, 'press report of final notification (Amar Ujala, 17 Dec 2023) (Beverly Park 1, MG Road)'),
  ('Palam Vihar Extension', 3, 'press (newzpapr ward list), verify; councillor Rakesh Yadav''s address is Palam Vihar Extension (ULB directory)'),
  ('Sector 21', 3, 'press (newzpapr ward list), verify'),
  ('Sector 22', 3, 'press (newzpapr ward list), verify; pockets A and B'),
  ('Mollahera', 3, 'press (newzpapr ward list), verify'),
  ('Nobel Enclave', 3, 'press (newzpapr ward list), verify'),
  ('Gurgaon One', 3, 'press (newzpapr ward list), verify'),
  ('Palam Vihar', 4, 'press report of final notification (Amar Ujala, 17 Dec 2023); Palam Vihar Sectors 1, 2, 3'),
  ('Sector 1', 4, 'press report of final notification (Amar Ujala, 17 Dec 2023); Palam Vihar Sector 1'),
  ('Sector 2', 4, 'press report of final notification (Amar Ujala, 17 Dec 2023); Palam Vihar Sector 2'),
  ('Sector 3', 4, 'press report of final notification (Amar Ujala, 17 Dec 2023); Palam Vihar Sector 3'),
  ('Sector 23', 4, 'press report of final notification (Amar Ujala, 17 Dec 2023); includes Sector 23A'),
  ('Chauma Khera', 4, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('New Palam Vihar', 5, 'press report of final notification (Amar Ujala, 17 Dec 2023); Phases 1-3; councillor Ram Avtar Rana (JJP) is based here'),
  ('Sector 109', 5, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 110', 5, 'press report of final notification (Amar Ujala, 17 Dec 2023); includes 110A'),
  ('Sector 111', 5, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 112', 5, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 113', 5, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 114', 5, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 115', 5, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Nihal Colony', 5, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sarai Alawardi', 5, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Bajghera', 5, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 102', 6, 'press report of final notification (Amar Ujala, 17 Dec 2023); includes 102A'),
  ('Sector 103', 6, 'press, verify; newzpapr lists it in the block that starts with Sector 102/102A'),
  ('Sector 106', 6, 'press, verify; newzpapr lists it in the block that starts with Sector 102/102A'),
  ('Daultabad', 6, 'press, verify; village; newzpapr lists it in the block that starts with Sector 102/102A; the Daultabad industrial area is in ward 34'),
  ('Dhankot', 6, 'press, verify; newzpapr lists it in the block that starts with Sector 102/102A'),
  ('Sector 105', 7, 'press, verify; newzpapr and GeoIQ (''Ward No.7, Sector 105'')'),
  ('Sector 9', 8, 'press report of final notification (Amar Ujala, 17 Dec 2023); includes 9A (9B is listed with ward 11)'),
  ('Bhawani Enclave', 8, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Ambedkar Nagar', 8, 'press report of final notification (Amar Ujala, 17 Dec 2023)')
on conflict (area) do update set ward = excluded.ward, note = excluded.note;

insert into public.area_wards (area, ward, note) values
  ('Devilal Colony', 8, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Ravi Nagar', 8, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Vishwakarma Colony', 8, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 10', 9, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Krishna Nagar', 9, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Vikas Nagar', 9, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Basai Enclave', 9, 'press report of final notification (Amar Ujala, 17 Dec 2023); Basai Enclave 1 and 2 (Basai village is listed with ward 11)'),
  ('Kadipur Enclave', 9, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Kadipur Industrial Area', 9, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Saraswati Enclave', 9, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Pace City 2', 9, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Udyog Vihar Phase 6', 9, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Khandsa', 9, 'press report of final notification (Amar Ujala, 17 Dec 2023); Khandsa village and Sector 37C; the old Khandsa industrial area is listed with ward 10'),
  ('Kadipur', 10, 'press (newzpapr ward list), verify; Kadipur village (its enclave and industrial area are in ward 9)'),
  ('Sector 10A', 10, 'press (newzpapr ward list), verify'),
  ('Pace City 1', 10, 'press (newzpapr ward list), verify'),
  ('Sector 37', 10, 'press, verify; newzpapr puts the old Khandsa industrial area (Sector 37) in ward 10 and Sector 37C in ward 9; split'),
  ('Shaktipur', 10, 'press (newzpapr ward list), verify'),
  ('Hari Nagar', 10, 'press (newzpapr ward list), verify'),
  ('Basai', 11, 'press (newzpapr ward list), verify; Basai village (Basai Enclave is in ward 9)'),
  ('Dhanwapur', 11, 'press (newzpapr ward list), verify; councillor of ward 7 is from Dhanwapur, so the village may be split with ward 7'),
  ('Gadoli', 11, 'press (newzpapr ward list), verify'),
  ('Surat Nagar 2', 11, 'press (newzpapr ward list), verify; Surat Nagar Phase 1 is in ward 34'),
  ('Sector 9B', 11, 'press (newzpapr ward list), verify'),
  ('Sector 37B', 11, 'press (newzpapr ward list), verify'),
  ('Sector 37D', 11, 'press (newzpapr ward list), verify'),
  ('Sector 100', 11, 'press (newzpapr ward list), verify'),
  ('Sector 101', 11, 'press (newzpapr ward list), verify'),
  ('Sector 104', 11, 'press (newzpapr ward list), verify'),
  ('Jharsa', 12, 'press report of final notification (Amar Ujala, 17 Dec 2023); Prem Puri (Jharsa) is listed with ward 13'),
  ('Mohyal Colony', 12, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Greenwood City', 12, 'press report of final notification (Amar Ujala, 17 Dec 2023); newzpapr''s draft list also shows it with the Kanhai/Sector 45 block (ward 21)'),
  ('Medicity', 12, 'press (newzpapr ward list), verify'),
  ('Sector 38', 12, 'press (newzpapr ward list), verify'),
  ('Sector 39', 12, 'press (newzpapr ward list), verify'),
  ('Islampur', 12, 'press (newzpapr ward list), verify'),
  ('Sector 33', 12, 'press, verify; newzpapr lists Sector 33 with Sector 38, Hans Enclave and Islampur; may belong to ward 15 (Malibu Towne/Sector 47)'),
  ('Hans Enclave', 12, 'press, verify; newzpapr lists it with Sector 38 and Islampur'),
  ('Sector 15', 13, 'press (newzpapr ward list), verify; Sector 15 Parts 1 and 2'),
  ('Kirti Nagar', 13, 'press (newzpapr ward list), verify'),
  ('Sector 31', 13, 'press (newzpapr ward list), verify'),
  ('Sector 40', 13, 'press (newzpapr ward list), verify; newzpapr''s draft list also shows Sector 40 with the Kanhai/Sector 45 block (ward 21)'),
  ('Prem Puri', 13, 'press (newzpapr ward list), verify; Prem Puri, Jharsa'),
  ('Sushant Lok 3', 14, 'press (newzpapr ward list), verify; includes Sushant Lok 3 Extension'),
  ('Sector 57', 14, 'press (newzpapr ward list), verify; Sushant Lok 3 is Sector 57; newzpapr also lists Sector 57 with the Wazirabad/Ardee City block (ward 22); split'),
  ('Sector 46', 14, 'press (newzpapr ward list), verify'),
  ('Jal Vihar', 14, 'press (newzpapr ward list), verify'),
  ('Indira Colony', 14, 'press (newzpapr ward list), verify; Indira Colony 1 and 2'),
  ('Sector 51', 14, 'press (newzpapr ward list), verify'),
  ('Mayfield Garden', 14, 'press (newzpapr ward list), verify; Mayfield Garden and Mayfield Colony (Sectors 50/51)')
on conflict (area) do update set ward = excluded.ward, note = excluded.note;

insert into public.area_wards (area, ward, note) values
  ('Tigra', 14, 'press (newzpapr ward list), verify'),
  ('Malibu Towne', 15, 'press report of final notification (Amar Ujala, 17 Dec 2023); councillor Bharati Harshana'),
  ('Sector 47', 15, 'press, verify; derived: Malibu Towne occupies Sector 47'),
  ('South City 2', 15, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 49', 15, 'press report of final notification (Amar Ujala, 17 Dec 2023); Uppal Southend (also Sector 49) is listed with ward 16; split'),
  ('Sector 50', 15, 'press report of final notification (Amar Ujala, 17 Dec 2023); Mayfield Garden (Sector 50/51) is listed with ward 14; split'),
  ('Nirvana Country', 15, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Rosewood City', 15, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 65', 15, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 66', 15, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Nangli Umarpur', 15, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Dharampur', 15, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Ghasola', 15, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Fazilpur Jharsa', 16, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Uppal Southend', 16, 'press report of final notification (Amar Ujala, 17 Dec 2023); Sector 49 itself is listed with ward 15; split'),
  ('Behrampur', 16, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 71', 16, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 72', 16, 'press report of final notification (Amar Ujala, 17 Dec 2023); listed as 72A; the printed list also says ''Sector 34'', almost certainly a misprint for 72'),
  ('Sector 73', 16, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 74', 16, 'press report of final notification (Amar Ujala, 17 Dec 2023); 74A is listed with ward 17'),
  ('Mohammadpur Jharsa', 17, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Narsinghpur', 17, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Begumpur Khatola', 17, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Kherki Daula', 17, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sihi', 17, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Darbaripur', 17, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Palra', 17, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 75', 17, 'press report of final notification (Amar Ujala, 17 Dec 2023); includes 74A and 75A'),
  ('Badshahpur', 18, 'press report of final notification (Amar Ujala, 17 Dec 2023); councillor Jyoti Jaildar'),
  ('Ramgarh ki Dhani', 18, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Noorpur', 18, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 67', 18, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 68', 18, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 69', 18, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 70', 18, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Bhondsi', 19, 'press report of final notification (Amar Ujala, 17 Dec 2023); councillor Raj Singh Amit Bhadana lists Bhondsi as his address'),
  ('Mohan Nagar', 19, 'press report of final notification (Amar Ujala, 17 Dec 2023); Mohan Nagar (Bhondsi)'),
  ('Sushant Lok 2', 20, 'press report of final notification (Amar Ujala, 17 Dec 2023); councillor Narayan Bhadana''s office is in Sushant Lok 2, Sector 55; newzpapr also lists Sushant Lok 2 with the ward 22 block, so the Sector 56/57 side may be split'),
  ('Sector 55', 20, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 58', 20, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 61', 20, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 62', 20, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Ghata', 20, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Kadarpur', 20, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Ullawas', 20, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Gwal Pahari', 20, 'press (newzpapr ward list), verify'),
  ('Bhandwari', 20, 'press (newzpapr ward list), verify'),
  ('Balola', 20, 'press (newzpapr ward list), verify'),
  ('Wazirabad', 21, 'press report of final notification (Amar Ujala, 17 Dec 2023); Amar Ujala''s ward 21 list starts with Wazirabad; newzpapr lists the village with the Ardee City/Sector 52-56 block (ward 22); the village spans Sectors 52-57 and is probably split'),
  ('Sushant Lok 1', 21, 'press, verify; newzpapr lists Sushant Lok 1, Sectors 29/30/44/45, Kanhai, Silokhera and South City 1 together, labelled ward 21 in one read and ward 19/20 (the Aug 2023 draft numbering) in another; blocks A and B appear with the DLF 4/Sector 43 block (ward 24)')
on conflict (area) do update set ward = excluded.ward, note = excluded.note;

insert into public.area_wards (area, ward, note) values
  ('South City 1', 21, 'press, verify; same block as Sushant Lok 1; Block I is listed with ward 12'),
  ('Sector 29', 21, 'press, verify; same block as Sushant Lok 1'),
  ('Sector 30', 21, 'press, verify; same block as Sushant Lok 1'),
  ('Sector 44', 21, 'press, verify; same block as Sushant Lok 1'),
  ('Sector 45', 21, 'press, verify; same block as Sushant Lok 1'),
  ('Sector 41', 21, 'press, verify; newzpapr draft block with Sectors 40/41/44/45'),
  ('Kanhai', 21, 'press, verify; same block as Sushant Lok 1'),
  ('Silokhera', 21, 'press, verify; same block as Sushant Lok 1'),
  ('Sector 32', 21, 'press, verify; derived: Silokhera village lies in Sector 32'),
  ('Saini Khera', 21, 'press, verify; same block as Sushant Lok 1'),
  ('Moti Vihar', 21, 'press, verify; same block as Sushant Lok 1'),
  ('Vijay Vihar', 21, 'press, verify; same block as Sushant Lok 1'),
  ('Jalvayu Vihar', 21, 'press, verify; Amar Ujala lists Jalvayu Vihar, Silokhera, Moti Vihar, Sector 30 and South City 1 together (ward number cut off in the snippet)'),
  ('Ardee City', 22, 'press (newzpapr ward list), verify; councillor Vikash Yadav (unopposed)'),
  ('Suncity', 22, 'press (newzpapr ward list), verify'),
  ('Sector 52', 22, 'press (newzpapr ward list), verify; includes 52A'),
  ('Sector 53', 22, 'press (newzpapr ward list), verify; councillor Aarti Yadav (ward 24) has described Sector 53 and DLF Phase 5 as her area; may be split with ward 24'),
  ('Sector 54', 22, 'press (newzpapr ward list), verify'),
  ('Sector 56', 22, 'press (newzpapr ward list), verify'),
  ('Chakkarpur', 23, 'press (newzpapr ward list), verify; councillor Kunal Yadav (#Chakkarpur)'),
  ('DLF Phase 1', 23, 'press (newzpapr ward list), verify'),
  ('Sector 26', 23, 'press, verify; derived: DLF Phase 1 occupies Sector 26'),
  ('Sector 28', 23, 'press (newzpapr ward list), verify'),
  ('Saraswati Vihar', 23, 'press (newzpapr ward list), verify'),
  ('Maruti Vihar', 23, 'press (newzpapr ward list), verify'),
  ('Maruti Kunj', 23, 'press (newzpapr ward list), verify'),
  ('DLF Phase 4', 24, 'press, verify; newzpapr lists DLF Phase 4, DLF Phase 5, Sectors 42/43/27 and Sushant Lok 1 blocks A-B in the block before its ward 23 heading; the only ward in the 19-24 group not otherwise accounted for is 24, whose councillor Aarti Yadav describes DLF Phase 5/Sector 53/Saraswati Kunj as her area'),
  ('DLF Phase 5', 24, 'press, verify; councillor Aarti Yadav describes DLF Phase 5, Sector 53 and Saraswati Kunj as her area (her page still carries the pre-2023 ward number 32)'),
  ('Saraswati Kunj', 24, 'press, verify; councillor Aarti Yadav''s stated area'),
  ('Sector 42', 24, 'press, verify; same newzpapr block as DLF Phase 4'),
  ('Sector 43', 24, 'press, verify; same newzpapr block as DLF Phase 4; the main part of Sushant Lok 1 (also Sector 43) is listed with ward 21; split'),
  ('Sector 27', 24, 'press, verify; same newzpapr block as DLF Phase 4'),
  ('Sector 17', 25, 'press report of final notification (Amar Ujala, 17 Dec 2023); councillor Anoop Singh (deputy mayor)'),
  ('Sector 14', 25, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 16', 25, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sukhrali', 25, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 12A', 25, 'press report of final notification (Amar Ujala, 17 Dec 2023); newzpapr lists Sector 12A with ward 26 (Rajiv Nagar/Sanjay Gram); may be split'),
  ('Chander Nagar', 25, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Canal Colony', 25, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Old DLF Colony', 25, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Anamika Enclave', 25, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Police Lines', 25, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('HVPNL Colony', 25, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Prem Nagar', 25, 'press report of final notification (Amar Ujala, 17 Dec 2023); Prem Nagar 2'),
  ('MDI', 25, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Air Force Station', 25, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Rajiv Nagar', 26, 'press (newzpapr ward list), verify; Rajiv Nagar and Rajiv Nagar West'),
  ('Sanjay Gram', 26, 'press (newzpapr ward list), verify'),
  ('Acharya Puri', 26, 'press (newzpapr ward list), verify'),
  ('Sheetla Colony', 26, 'press (newzpapr ward list), verify; blocks A and B')
on conflict (area) do update set ward = excluded.ward, note = excluded.note;

insert into public.area_wards (area, ward, note) values
  ('Civil Lines', 27, 'press report of final notification (Amar Ujala, 17 Dec 2023); councillor Ashish Gupta'),
  ('Friends Colony', 27, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Baraf Khana', 27, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Roshanpura', 27, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Adarsh Nagar', 27, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Indrapuri', 27, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Om Nagar', 28, 'press (newzpapr ward list), verify; councillor Dharambir Bhangrola (senior deputy mayor)'),
  ('Rajeev Colony', 28, 'press (newzpapr ward list), verify'),
  ('Shanti Nagar', 28, 'press (newzpapr ward list), verify'),
  ('Raj Nagar', 28, 'press (newzpapr ward list), verify'),
  ('Shivaji Park', 28, 'press (newzpapr ward list), verify'),
  ('Gandhi Nagar', 28, 'press (newzpapr ward list), verify'),
  ('Shivaji Nagar', 29, 'press, verify; Amar Ujala lists Shivaji Nagar in the block immediately before its ward 30 heading; newzpapr also puts it in ward 29'),
  ('Firoz Gandhi Colony', 29, 'press, verify; same Amar Ujala block as Shivaji Nagar'),
  ('Auto Market', 29, 'press, verify; same Amar Ujala block as Shivaji Nagar'),
  ('Amar Colony', 29, 'press, verify; same Amar Ujala block as Shivaji Nagar'),
  ('Shakti Nagar', 29, 'press, verify; same Amar Ujala block as Shivaji Nagar'),
  ('Laxmi Garden', 29, 'press, verify; same Amar Ujala block as Shivaji Nagar'),
  ('Aath Marla', 29, 'press, verify; same Amar Ujala block as Shivaji Nagar'),
  ('Madanpuri', 30, 'press report of final notification (Amar Ujala, 17 Dec 2023); councillor Madhu Batra'),
  ('Arjun Nagar', 30, 'press report of final notification (Amar Ujala, 17 Dec 2023); newzpapr puts Arjun Nagar in ward 29 and ''Arjun Vihar'' in ward 30; verify'),
  ('Ram Nagar', 30, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Vijay Park', 30, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Nehru Lane', 30, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Jyoti Park', 30, 'press (newzpapr ward list), verify; newzpapr lists Jyoti Park with both ward 30 and ward 32'),
  ('Dayanand Colony', 31, 'press report of final notification (Amar Ujala, 17 Dec 2023); councillor Dalip Kumar Sahani'),
  ('Ashok Puri', 31, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Mahavir Pura', 31, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Jawahar Nagar', 31, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 7', 32, 'press report of final notification (Amar Ujala, 17 Dec 2023); includes Sector 7 Extension and Housing Board Colony'),
  ('Shivpuri', 32, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Krishna Colony', 32, 'press (newzpapr ward list), verify'),
  ('Housing Board Colony', 32, 'press (newzpapr ward list), verify; Sector 7 Housing Board'),
  ('Laxman Vihar', 33, 'press (newzpapr ward list), verify; Phases 1 and 2; Amar Ujala''s snippet runs Laxman Vihar into its ward 30 list, newzpapr gives ward 33; councillor Sarika Bhardwaj'),
  ('Sector 4', 33, 'press (newzpapr ward list), verify; same caveat as Laxman Vihar'),
  ('Cancan Enclave', 33, 'press (newzpapr ward list), verify'),
  ('Rajendra Park', 34, 'press report of final notification (Amar Ujala, 17 Dec 2023); newzpapr also shows part of Rajendra Park with Sector 105 (ward 7); split'),
  ('Daultabad Industrial Area', 34, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Tek Chand Nagar', 34, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Surat Nagar', 34, 'press report of final notification (Amar Ujala, 17 Dec 2023); Surat Nagar Phase 1 (Phase 2 is listed with ward 11)'),
  ('Ashok Vihar', 35, 'press report of final notification (Amar Ujala, 17 Dec 2023); Ashok Vihar and Ashok Vihar Phase 2; councillor Parminder Kataria'),
  ('Sector 5', 35, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Sector 6', 35, 'press report of final notification (Amar Ujala, 17 Dec 2023)'),
  ('Bhim Garh Kheri', 35, 'press report of final notification (Amar Ujala, 17 Dec 2023); Phases 1-3'),
  ('Apna Enclave', 35, 'press report of final notification (Amar Ujala, 17 Dec 2023)')
on conflict (area) do update set ward = excluded.ward, note = excluded.note;
