// Generates supabase/seed.sql from site/data.js so the database's master data
// matches what the site renders. Run: node scripts/export-seed.mjs
import { readFileSync, writeFileSync } from "node:fs";
import vm from "node:vm";

const src = readFileSync(new URL("../site/data.js", import.meta.url), "utf8");
const sandbox = { window: {} };
vm.runInNewContext(src, sandbox);
const D = sandbox.window.GVF;

const q = (v) => (v == null ? "null" : "'" + String(v).replace(/'/g, "''") + "'");
const arr = (a) => "array[" + a.map(q).join(",") + "]::text[]";

let sql = "-- Generated by scripts/export-seed.mjs from site/data.js. Do not edit by hand.\n";
sql += "insert into public.issue_types (id, label, label_hi, agency, owns, channels, ladder, role_ids, sort) values\n";
sql += D.CATS.map((c, i) =>
  `  (${q(c.id)}, ${q(c.label)}, ${q(c.hl)}, ${q(c.agency)}, ${q(c.owns)}, ${q(JSON.stringify(c.channels))}::jsonb, ${q(JSON.stringify(c.ladder))}::jsonb, ${c.roles && c.roles.length ? arr(c.roles) : "'{}'::text[]"}, ${i})`
).join(",\n");
sql += "\non conflict (id) do update set label = excluded.label, label_hi = excluded.label_hi, agency = excluded.agency, owns = excluded.owns, channels = excluded.channels, ladder = excluded.ladder, role_ids = excluded.role_ids, sort = excluded.sort;\n\n";

sql += "insert into public.wards (ward, councillor, party_as_elected) values\n";
sql += D.WARDS.map((w) => `  (${w[0]}, ${q(w[1])}, ${q(w[2])})`).join(",\n");
sql += "\non conflict (ward) do update set councillor = excluded.councillor, party_as_elected = excluded.party_as_elected;\n";

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log(`seed.sql written: ${D.CATS.length} issue types, ${D.WARDS.length} wards`);
